class CompliancePermissions {
  const CompliancePermissions({
    required this.canView,
    required this.canCreate,
    required this.canEdit,
    required this.canDelete,
    required this.canExport,
    required this.canUpload,
    required this.canDownload,
    required this.canApprove,
  });
  final bool canView,
      canCreate,
      canEdit,
      canDelete,
      canExport,
      canUpload,
      canDownload,
      canApprove;
  bool allows(String permission) => switch (permission) {
    'complianceReports.view' => canView,
    'complianceReports.generate' => canCreate || canEdit,
    'complianceReports.export' => canExport,
    'complianceReports.print' => canExport,
    'complianceQueries.view' => canView,
    'complianceQueries.create' => canCreate,
    'complianceQueries.edit' => canEdit,
    'complianceQueries.assign' => canEdit,
    'complianceQueries.resolve' => canEdit || canApprove,
    'complianceQueries.delete' => canDelete,
    'complianceNotices.view' => canView,
    'complianceNotices.create' => canCreate,
    'complianceNotices.edit' => canEdit,
    'complianceNotices.assign' => canEdit,
    'complianceNotices.delete' => canDelete,
    'complianceLegalCases.view' => canView,
    'complianceLegalCases.create' => canCreate,
    'complianceLegalCases.edit' => canEdit,
    'complianceLegalCases.delete' => canDelete,
    'complianceDocuments.view' => canView,
    'complianceDocuments.upload' => canUpload,
    'complianceDocuments.download' => canDownload,
    'complianceDocuments.share' => canExport,
    'complianceDocuments.delete' => canDelete,
    'complianceAudit.view' => canApprove,
    'complianceSchedules.manage' => canApprove,
    _ => false,
  };
}
